version: '3.1'

services:

  mongo:
    image: mongo:4.2.2
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: treinamento
    ports:
        - 27017:27017
    #command: --smallfiles
    command: --auth

  mongo-express:
    image: mongo-express
    #restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      MONGO_INITDB_DATABASE: treinamento
      